name: "nuget Ifx.Servi—Åes.Contracts"

on:
  workflow_dispatch: 

env:
  DOTNET_INSTALL_DIR: "./.dotnet"
  
jobs:
  build:
    
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: '8.0.x'
      - name: Restore Dependencies
        run: dotnet restore
      - name: Pack
        run: dotnet pack DontPanicLabs.Ifx.Services.Contracts/DontPanicLabs.Ifx.Services.Contracts.csproj
      - name: Publish Package
        run: dotnet nuget push **\*.nupkg -s 'https://api.nuget.org/v3/index.json' -k ${{ secrets.NUGET_APIKEY }}
      - name: Publish Symbols
        run: dotnet nuget push **\*.snupkg -s 'https://api.nuget.org/v3/index.json' -k ${{ secrets.NUGET_APIKEY }}
